name: Deploy to GCP
on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        
    - name: Configure Docker
      run: gcloud auth configure-docker
        
    - name: Build & Push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/spring-app:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/spring-app:${{ github.sha }}
        
    - name: Deploy to GCP
      run: |
        gcloud compute instances create-with-container spring-instance-${{ github.sha }} \
          --container-image gcr.io/${{ secrets.GCP_PROJECT_ID }}/spring-app:${{ github.sha }} \
          --machine-type=e2-medium \
          --tags=http-server \
          --zone=${{ secrets.GCP_REGION }} \
          --metadata=startup-script='#! /bin/bash
          sudo apt-get update
          sudo apt-get install -y nginx
          '
        
    - name: Create Firewall Rule
      run: |
        gcloud compute firewall-rules create allow-http \
          --allow tcp:8080 \
          --target-tags http-server \
          --description="Allow HTTP traffic"