name: Deploy to GCP
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # Authenticate to Google Cloud
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        token_format: 'access_token'
        
    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      
    # Configure Docker for GCR
    - name: Configure Docker
      run: |
        gcloud auth configure-docker gcr.io --quiet
        
    # Build and push the Docker image
    - name: Build & Push Docker image
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "Building image for project: $GCP_PROJECT_ID"
        docker build -t "gcr.io/$GCP_PROJECT_ID/spring-app:$IMAGE_TAG" .
        echo "Pushing image to GCR..."
        docker push "gcr.io/$GCP_PROJECT_ID/spring-app:$IMAGE_TAG"
        
    # Deploy to Compute Engine
    - name: Deploy to Compute Engine
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        gcloud config set project $GCP_PROJECT_ID
        gcloud compute instances create-with-container spring-instance-$IMAGE_TAG \
          --container-image "gcr.io/$GCP_PROJECT_ID/spring-app:$IMAGE_TAG" \
          --machine-type=e2-medium \
          --tags=http-server \
          --zone=${{ secrets.GCP_REGION }} \
          --metadata=startup-script='#! /bin/bash
          sudo apt-get update
          sudo apt-get install -y nginx
          '